# Generated by Django 4.0.4 on 2022-05-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietary', models.CharField(max_length=35, verbose_name='name of the proprietary of the account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateField()),
                ('quantity', models.CharField(max_length=99, verbose_name='Quantity of the transaction')),
                ('type', models.CharField(max_length=99, verbose_name='Type of the transaction')),
            ],
        ),
    ]
