# Generated by Django 4.0.4 on 2022-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='proprietary',
            field=models.CharField(default='', max_length=35, verbose_name='Account email of the proprietary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='proprietary',
            field=models.CharField(max_length=35, verbose_name='email of the proprietary of the account'),
        ),
    ]
