# Generated by Django 4.0.4 on 2022-05-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_type_transaction_proprietary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(max_length=99, verbose_name='Quantity of the transaction'),
        ),
    ]
