# Generated by Django 4.0.4 on 2022-05-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.CharField(max_length=6, verbose_name='Date of transaction'),
        ),
    ]
